### ISSUE TITLE
Image is not showing after taking screenshot.

### ISSUE THREAD

**Issue by karthi72** [armcha/Screenshot-observer#1]
I have added this library in my project and also started service.After taking screenshot it is going to the screenshot image displaying activity but image view is not showing the screenshot taken.Even I have tried with displaying image through Picasso.

**Comment by armcha** [comment]
@karthi72 Are you receiving image uri?
```String path = getIntent().getStringExtra(PATH_INTENT_KEY);```

**Comment by karthi72** [comment]
Yes,in service am receiving extras and as well as URI.

**Comment by armcha** [comment]
@karthi72 I think bitmap decode method isn't work. 
Try to get bitmap from file yourself. Thanks

**Comment by karthi72** [comment]
`String path = getIntent().getStringExtra(PATH_INTENT_KEY);`
`Picasso.with(getApplicationContext()).load("file://"+path).config(Bitmap.Config.RGB_565).fit().centerCrop().into(screenShotImage);  `        
Fixed by this.

**Comment by armcha** [comment]
Great, Thanks.

**Comment by karthi72** [comment]
shall i make a commit and update your code else you itself update the code.

**Comment by armcha** [comment]
It will be great!!

**Comment by karthi72** [comment]
Also I need a help.Please share your email address.I will share my problem am facing.

**Comment by armcha** [comment]
armcha01@gmail.com

**Comment by karthi72** [comment]
I have sent u a mail.please check it out.And approve the change made by myself.
